#!/usr/bin/env python2
# This script is here so that you can double click from file managers like thunar.
# Thunar disabled double-clicking on shell scripts because they often don't work like that.
import os, sys
path_parts = sys.argv[0].split(os.sep)
path_parts[-1] = '.' + path_parts[-1]
run = os.sep.join(path_parts)
os.execv(run, [run] + sys.argv[1:])
